# Generated by Django 3.1.5 on 2021-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('quantity', models.IntegerField(max_length=2)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('BOUGHT', 'bought'), ('NOT AVAILABLE', 'not available')], default='PENDING', max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
