# Generated by Django 3.1.5 on 2021-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerybag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
